// tests/appGenerator.test.js
const generateApp = require('../src/appGenerator');

test('generate an app with given name and type', () => {
    const app = generateApp('MyApp', 'Web');
    expect(app.name).toBe('MyApp');
    expect(app.type).toBe('Web');
    expect(app.description).toContain('MyApp is a Web application generated by aenzbi AI.');
});
