// src/appGenerator.js
function generateApp(name, type) {
    return {
        name: name,
        type: type,
        createdAt: new Date(),
        description: `${name} is a ${type} application generated by aenzbi AI.`,
    };
}

module.exports = generateApp;
